//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaCategoryCollectionType
    {
        public long CollectionTypeID { get; set; }
        public string CollectionTypeName { get; set; }
        public Nullable<System.DateTime> CollectionTypeDateCreated { get; set; }
        public Nullable<System.DateTime> CollectionTypeDateModified { get; set; }
        public Nullable<System.DateTime> CollectionTypeDateDeleted { get; set; }
    }
}
