//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaService
    {
        public long ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<decimal> ServiceRate { get; set; }
        public Nullable<long> ServicePaymentTypeID { get; set; }
        public string ServiceLocationLongitude { get; set; }
        public string ServiceLocationLatitude { get; set; }
        public Nullable<long> ServiceAreaRangeID { get; set; }
        public Nullable<long> ServiceCategoryID { get; set; }
        public string ServiceSubCategoryID { get; set; }
        public Nullable<long> ServiceExperienceLevelID { get; set; }
        public string ServiceUserID { get; set; }
        public Nullable<System.DateTime> ServiceDateCreated { get; set; }
        public Nullable<System.DateTime> ServiceDateModified { get; set; }
        public Nullable<System.DateTime> ServiceDateDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
