//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QaaryaEntities : DbContext
    {
        public QaaryaEntities()
            : base("name=QaaryaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<QaaryaCategory> QaaryaCategories { get; set; }
        public virtual DbSet<QaaryaCategoryCollection> QaaryaCategoryCollections { get; set; }
        public virtual DbSet<QaaryaCategoryCollectionType> QaaryaCategoryCollectionTypes { get; set; }
        public virtual DbSet<QaaryaGender> QaaryaGenders { get; set; }
        public virtual DbSet<QaaryaMedia> QaaryaMedias { get; set; }
        public virtual DbSet<QaaryaLocation> QaaryaLocations { get; set; }
        public virtual DbSet<QaaryaProfile> QaaryaProfiles { get; set; }
        public virtual DbSet<QaaryaJobHiring> QaaryaJobHirings { get; set; }
        public virtual DbSet<QaaryaRatingReview> QaaryaRatingReviews { get; set; }
        public virtual DbSet<QaaryaService> QaaryaServices { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
