//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaGender
    {
        public long GenderID { get; set; }
        public string GenderDescription { get; set; }
        public Nullable<System.DateTime> GenderDateCreated { get; set; }
        public Nullable<System.DateTime> GenderDateModified { get; set; }
        public Nullable<System.DateTime> GenderDateDeleted { get; set; }
    }
}
