//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaLocation
    {
        public long LocationID { get; set; }
        public string LocationUserID { get; set; }
        public string LocationDescription { get; set; }
        public string LocationLabel { get; set; }
        public string LocationStreetNumber { get; set; }
        public string LocationStreetName { get; set; }
        public string LocationCity { get; set; }
        public string LocationState { get; set; }
        public string LocationPostalCode { get; set; }
        public string LocationCountry { get; set; }
        public string LocationLatitude { get; set; }
        public string LocationLongitude { get; set; }
        public Nullable<System.DateTime> LocationDateCreated { get; set; }
        public Nullable<System.DateTime> LocationDateModified { get; set; }
        public Nullable<System.DateTime> LocationDateDeleted { get; set; }
    }
}
