//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaCategory
    {
        public long CategoryID { get; set; }
        public Nullable<long> CategoryCategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> CategoryDateCreated { get; set; }
        public Nullable<System.DateTime> CategoryDateModified { get; set; }
        public Nullable<System.DateTime> CategoryDateDeleted { get; set; }
    }
}
