//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaRatingReview
    {
        public long RatingID { get; set; }
        public Nullable<long> RatingServiceID { get; set; }
        public Nullable<long> RatingHireID { get; set; }
        public string RatingClientID { get; set; }
        public string RatingVendorID { get; set; }
        public Nullable<int> RatingRateClient { get; set; }
        public Nullable<int> RatingRateVendor { get; set; }
        public string RatingReviewClient { get; set; }
        public string RatingReviewVendor { get; set; }
        public Nullable<System.DateTime> RatingDateCreated { get; set; }
        public Nullable<System.DateTime> RatingDateModified { get; set; }
        public Nullable<System.DateTime> RatingDateDeleted { get; set; }
    }
}
