//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QaaryaProfile()
        {
            this.QaaryaMedias = new HashSet<QaaryaMedia>();
        }
    
        public long ProfileID { get; set; }
        public string ProfileFirstName { get; set; }
        public string ProfileLastName { get; set; }
        public Nullable<System.DateTime> ProfileDateofBirth { get; set; }
        public Nullable<long> ProfileGenderID { get; set; }
        public string ProfileAddressLocation { get; set; }
        public string ProfileUserID { get; set; }
        public Nullable<System.DateTime> ProfileDateCreated { get; set; }
        public Nullable<System.DateTime> ProfileDateModified { get; set; }
        public Nullable<System.DateTime> ProfileDateDeleted { get; set; }
        public string ProfileDescription { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QaaryaMedia> QaaryaMedias { get; set; }
    }
}
