//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaJobHiring
    {
        public long JobHireID { get; set; }
        public string JobHireClientID { get; set; }
        public string JobHireVendorID { get; set; }
        public Nullable<long> JobHireServiceID { get; set; }
        public Nullable<bool> JobHireConfirmedByClient { get; set; }
        public Nullable<bool> JobHireConfirmedByVendor { get; set; }
        public Nullable<System.DateTime> JobHireDateCreated { get; set; }
        public Nullable<System.DateTime> JobHireDateModified { get; set; }
        public Nullable<System.DateTime> JobHireDateDeleted { get; set; }
    }
}
