//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaarya.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QaaryaCategoryCollection
    {
        public long CategoryCollectionID { get; set; }
        public Nullable<long> CategoryCollectionTypeID { get; set; }
        public Nullable<int> CategoryCollectionValue { get; set; }
        public string CategoryCollectionName { get; set; }
        public Nullable<System.DateTime> CategoryCollectionDateCreated { get; set; }
        public Nullable<System.DateTime> CategoryCollectionDateModified { get; set; }
        public Nullable<System.DateTime> CatetgoryCollectionDateDeleted { get; set; }
    }
}
